### ISSUE TITLE
Multiple Button tap causes app crash

### ISSUE THREAD

**Issue by TheGuyDangerous** [TheGuyDangerous/Voicerra#21]
Happening in the continuous transcription page , where  start button causes the app to crash , when tapped more than once (Unlike the ideal situation where the start button is followed by the stop button.)

A Temporary solution to it , would be to disable each button after the other is pressed.
A neat solution would be to have a single button control for both the starting and stopping of the sound stream property (listening status).

**Comment by chandansgowda** [comment]
Hey @TheGuyDangerous 
Shall I take this up?

**Comment by TheGuyDangerous** [comment]
Sure !! @chandansgowda go ahead !!! It would be a great help 😊✨

For now , i have removed the api key used in the continuous.dart file (line 16 to be precise). If you want to test the functionality , tell me , and I'll provide you a temporary api key for testing purposes.

**Comment by chandansgowda** [comment]
Thanks @TheGuyDangerous 
Please share a temporary API key.

**Comment by chandansgowda** [comment]
Hey @TheGuyDangerous 
I have implemented a single button to start/stop the recording stream. Refer to my latest commit [here](https://github.com/chandansgowda/Voicerra/commit/b860e280983d59ea49c44df097a7fee289ac0c96)
I don't think testing is required here since I have used the same function calls as done before. I'll raise a PR if you confirm.
Thanks

**Comment by TheGuyDangerous** [comment]
Yupp .. everything works fine , as intended.
Send in the Pr , and I'll be happy to merge it ☺️ !!

**Comment by chandansgowda** [comment]
Thanks!
PR - #22
